// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4SAcoGZ909GKiH2hOXmrfZI2JT_ETis8',
    appId: '1:469200334388:web:d1f415840cc42c083c6461',
    messagingSenderId: '469200334388',
    projectId: 'myproject-mobile-13131',
    authDomain: 'myproject-mobile-13131.firebaseapp.com',
    storageBucket: 'myproject-mobile-13131.firebasestorage.app',
    measurementId: 'G-SEQWKT4Q5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUyFgqi0izgkhpFRaBerbPmJplpHcEgPs',
    appId: '1:469200334388:android:b7d724dd0a70af133c6461',
    messagingSenderId: '469200334388',
    projectId: 'myproject-mobile-13131',
    storageBucket: 'myproject-mobile-13131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zNJ3cw0ts1Jb_Due6MN1B3w-XHqx1v4',
    appId: '1:469200334388:ios:814cf789705b876b3c6461',
    messagingSenderId: '469200334388',
    projectId: 'myproject-mobile-13131',
    storageBucket: 'myproject-mobile-13131.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zNJ3cw0ts1Jb_Due6MN1B3w-XHqx1v4',
    appId: '1:469200334388:ios:814cf789705b876b3c6461',
    messagingSenderId: '469200334388',
    projectId: 'myproject-mobile-13131',
    storageBucket: 'myproject-mobile-13131.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4SAcoGZ909GKiH2hOXmrfZI2JT_ETis8',
    appId: '1:469200334388:web:2048cff14d59e2913c6461',
    messagingSenderId: '469200334388',
    projectId: 'myproject-mobile-13131',
    authDomain: 'myproject-mobile-13131.firebaseapp.com',
    storageBucket: 'myproject-mobile-13131.firebasestorage.app',
    measurementId: 'G-K9NZC9THBH',
  );
}
